/**
 * Unit + integration tests for scripts/audit-compliance.ts.
 *
 * Pure evaluators (isGeneratedFile, findBadImports, findBareThrows,
 * readDependencies) are tested with synthetic inputs.
 *
 * The end-to-end pass exercises runComplianceAgainst with fixture
 * files + a mocked verify-endpoints payload, so the test is hermetic
 * (no subprocess invocation, no real SDK scan).
 */

import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import ts from "typescript";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  runComplianceAgainst,
  isGeneratedFile,
  findBadImports,
  findBareThrows,
  readDependencies,
  type VerifyEndpointsPayload,
} from "../../scripts/audit-compliance.js";
import { stableStringify } from "../../scripts/audit-lib/render.js";
import type { AuditContext } from "../../scripts/audit-lib/types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = resolve(__dirname, "fixtures/compliance");

// ---------------------------------------------------------------------------
// Pure-evaluator unit tests
// ---------------------------------------------------------------------------

describe("isGeneratedFile", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = mkdtempSync(resolve(tmpdir(), "audit-compliance-test-"));
  });
  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it("returns true when the header mentions openapi-typescript", () => {
    const f = resolve(tmp, "g.ts");
    writeFileSync(f, "// generated by openapi-typescript\nexport interface X {}\n");
    expect(isGeneratedFile(f)).toBe(true);
  });

  it("returns true when the header says 'do not edit' (case-insensitive)", () => {
    const f = resolve(tmp, "g.ts");
    writeFileSync(f, "// Auto-generated — Do Not Edit\nexport interface X {}\n");
    expect(isGeneratedFile(f)).toBe(true);
  });

  it("returns true for the actual SDK header wording", () => {
    // The phrasing used in this codebase's real src/types/generated.ts.
    const f = resolve(tmp, "g.ts");
    writeFileSync(
      f,
      "// Auto-generated from Teamleader Focus API OpenAPI spec\n// Do not edit manually — run `npm run generate` to regenerate\n",
    );
    expect(isGeneratedFile(f)).toBe(true);
  });

  it("returns false for a hand-rolled types file with no header", () => {
    const f = resolve(tmp, "g.ts");
    writeFileSync(f, "export interface X { y: number; }\n");
    expect(isGeneratedFile(f)).toBe(false);
  });
});

describe("findBadImports (principle III)", () => {
  it("flags node:* specifiers", () => {
    const bad = findBadImports([
      { module: "node:fs", type_only: false, line: 1 },
      { module: "node:path", type_only: false, line: 2 },
    ]);
    expect(bad.map((b) => b.module)).toEqual(["node:fs", "node:path"]);
  });

  it("flags bare Node built-ins (fs, path, etc.)", () => {
    const bad = findBadImports([
      { module: "fs", type_only: false, line: 1 },
      { module: "crypto", type_only: false, line: 2 },
    ]);
    expect(bad.length).toBe(2);
  });

  it("does NOT flag Web Standard APIs or relative imports", () => {
    const bad = findBadImports([
      { module: "./client.js", type_only: false, line: 1 },
      { module: "typescript", type_only: false, line: 2 }, // devDep import; not a runtime concern in src
      { module: "../types/common.js", type_only: true, line: 3 },
    ]);
    // typescript is a tricky case — for the principle, what matters is `node:*` and built-ins.
    // typescript itself is a devDep; runtime portability doesn't care about it in scripts/.
    expect(bad.map((b) => b.module)).not.toContain("./client.js");
    expect(bad.map((b) => b.module)).not.toContain("../types/common.js");
  });
});

describe("findBareThrows (principle V)", () => {
  const newThrow = (name: string, line = 1) => ({
    ctor_class_name: name,
    ctor_class_names_all: name ? [name] : [],
    kind: "new" as const,
    line,
  });
  const rethrow = (line = 1) => ({
    ctor_class_name: "",
    ctor_class_names_all: [],
    kind: "rethrow" as const,
    line,
  });
  const conditionalThrow = (names: string[], line = 1) => ({
    ctor_class_name: names[0] ?? "",
    ctor_class_names_all: names,
    kind: "conditional" as const,
    line,
  });

  it("flags `throw new Error(...)`", () => {
    const bad = findBareThrows([newThrow("Error")]);
    expect(bad.length).toBe(1);
  });

  it("flags `throw new TypeError(...)` and other non-Teamleader ctors", () => {
    const bad = findBareThrows([newThrow("TypeError", 1), newThrow("RangeError", 2)]);
    expect(bad.length).toBe(2);
  });

  it("does NOT flag TeamleaderFocus* subclasses", () => {
    const bad = findBareThrows([
      newThrow("TeamleaderFocusValidationError", 1),
      newThrow("TeamleaderFocusAuthenticationError", 2),
      newThrow("TeamleaderFocusError", 3),
    ]);
    expect(bad).toEqual([]);
  });

  it("does NOT flag re-throws (`throw <identifier>`)", () => {
    const bad = findBareThrows([rethrow()]);
    expect(bad).toEqual([]);
  });

  it("does NOT flag `throw new DOMException(...)` — Web standard abort signal", () => {
    const bad = findBareThrows([newThrow("DOMException")]);
    expect(bad).toEqual([]);
  });

  it("does NOT flag conditional throws where every branch is acceptable", () => {
    // e.g. `throw signal.reason instanceof Error ? signal.reason : new DOMException(...)`
    const bad = findBareThrows([conditionalThrow(["DOMException"])]);
    expect(bad).toEqual([]);
  });

  it("DOES flag conditional throws if any branch constructs a non-acceptable type", () => {
    const bad = findBareThrows([conditionalThrow(["DOMException", "Error"])]);
    expect(bad.length).toBe(1);
  });
});

describe("readDependencies (principle IV)", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = mkdtempSync(resolve(tmpdir(), "audit-compliance-test-"));
  });
  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it("returns empty for {}", () => {
    const f = resolve(tmp, "package.json");
    writeFileSync(f, '{"dependencies": {}}');
    expect(readDependencies(f)).toEqual([]);
  });

  it("returns sorted names when deps are declared", () => {
    const f = resolve(tmp, "package.json");
    writeFileSync(
      f,
      '{"dependencies": {"lodash": "^4.0.0", "axios": "^1.0.0"}}',
    );
    expect(readDependencies(f)).toEqual(["axios", "lodash"]);
  });

  it("returns empty when the dependencies key is absent", () => {
    const f = resolve(tmp, "package.json");
    writeFileSync(f, '{"name": "x"}');
    expect(readDependencies(f)).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// End-to-end pass via runComplianceAgainst with fixture files
// ---------------------------------------------------------------------------

function buildFixtureProgram(files: string[]): ts.Program {
  return ts.createProgram({
    rootNames: files,
    options: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.NodeNext,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      noEmit: true,
      strict: false,
      skipLibCheck: true,
    },
  });
}

const CTX: AuditContext = {
  sha: "0000000000000000000000000000000000000000",
  branch: "test",
  // Use FIXTURES_DIR as repoRoot so paths come out as "src/bad-imports.ts" etc.
  repoRoot: FIXTURES_DIR,
};

const FIXTURE_FILES = [
  resolve(FIXTURES_DIR, "src/bad-imports.ts"),
  resolve(FIXTURES_DIR, "src/bad-throws.ts"),
  resolve(FIXTURES_DIR, "src/good.ts"),
  resolve(FIXTURES_DIR, "src/resources/has-coverage.ts"),
  resolve(FIXTURES_DIR, "src/resources/missing-coverage.ts"),
  resolve(FIXTURES_DIR, "good-package/package.json"),
  resolve(FIXTURES_DIR, "bad-package/package.json"),
];

// Mock verify-endpoints payload. missingCoverageResource.someUntestedMethod
// should be flagged; has-coverage's methods should pass.
const MOCK_VEP: VerifyEndpointsPayload = {
  schema_version: "1",
  endpoints_total: 4,
  exempted: [],
  missing_live_coverage: [
    {
      endpoint: "/missingCoverage.someUntestedMethod",
      operation_id: "missingCoverage.someUntestedMethod",
      resource: "missingCoverage",
      method: "someUntestedMethod",
    },
  ],
  missing_sdk_method: [],
};

describe("runComplianceAgainst (end-to-end with fixtures)", () => {
  it("flags principle III on the bad-imports fixture", async () => {
    const program = buildFixtureProgram(
      FIXTURE_FILES.filter((f) => f.endsWith(".ts")),
    );
    const result = await runComplianceAgainst(FIXTURE_FILES, program, MOCK_VEP, CTX);

    const row = result.artifact.rows.find((r) => r.file === "src/bad-imports.ts")!;
    expect(row).toBeDefined();
    expect(row.cells.III).toBe("no");
    expect(row.finding_ids.length).toBeGreaterThan(0);

    const findings = result.findings.filter((f) => row.finding_ids.includes(f.id));
    expect(findings.some((f) => f.principle === "III")).toBe(true);
  });

  it("flags principle V on the bad-throws fixture", async () => {
    const program = buildFixtureProgram(
      FIXTURE_FILES.filter((f) => f.endsWith(".ts")),
    );
    const result = await runComplianceAgainst(FIXTURE_FILES, program, MOCK_VEP, CTX);

    const row = result.artifact.rows.find((r) => r.file === "src/bad-throws.ts")!;
    expect(row.cells.V).toBe("no");
    expect(row.finding_ids.length).toBeGreaterThan(0);
  });

  it("flags principle IV on bad-package/package.json", async () => {
    const program = buildFixtureProgram(
      FIXTURE_FILES.filter((f) => f.endsWith(".ts")),
    );
    const result = await runComplianceAgainst(FIXTURE_FILES, program, MOCK_VEP, CTX);

    const row = result.artifact.rows.find((r) => r.file === "bad-package/package.json")!;
    expect(row.cells.IV).toBe("no");
    const finding = result.findings.find((f) => row.finding_ids.includes(f.id));
    expect(finding?.principle).toBe("IV");
    expect(finding?.message).toContain("axios");
    expect(finding?.message).toContain("lodash");
  });

  it("passes principle IV on good-package/package.json", async () => {
    const program = buildFixtureProgram(
      FIXTURE_FILES.filter((f) => f.endsWith(".ts")),
    );
    const result = await runComplianceAgainst(FIXTURE_FILES, program, MOCK_VEP, CTX);

    const row = result.artifact.rows.find((r) => r.file === "good-package/package.json")!;
    expect(row.cells.IV).toBe("yes");
    expect(row.finding_ids).toEqual([]);
  });

  it("flags principle VI partially on missing-coverage and clears it on has-coverage", async () => {
    const program = buildFixtureProgram(
      FIXTURE_FILES.filter((f) => f.endsWith(".ts")),
    );
    const result = await runComplianceAgainst(FIXTURE_FILES, program, MOCK_VEP, CTX);

    const missing = result.artifact.rows.find(
      (r) => r.file === "src/resources/missing-coverage.ts",
    )!;
    expect(missing.cells.VI).toBe("partial");

    const has = result.artifact.rows.find(
      (r) => r.file === "src/resources/has-coverage.ts",
    )!;
    expect(has.cells.VI).toBe("yes");
  });

  it("marks good.ts cells as yes for III/V and n/a for the others", async () => {
    const program = buildFixtureProgram(
      FIXTURE_FILES.filter((f) => f.endsWith(".ts")),
    );
    const result = await runComplianceAgainst(FIXTURE_FILES, program, MOCK_VEP, CTX);

    const row = result.artifact.rows.find((r) => r.file === "src/good.ts")!;
    expect(row.cells.III).toBe("yes");
    expect(row.cells.V).toBe("yes");
    expect(row.cells.I).toBe("n/a");
    expect(row.cells.II).toBe("n/a");
    expect(row.cells.IV).toBe("n/a");
    expect(row.cells.VI).toBe("n/a");
    expect(row.finding_ids).toEqual([]);
  });

  it("produces byte-identical output on two runs with the same inputs (FR-009)", async () => {
    const program1 = buildFixtureProgram(
      FIXTURE_FILES.filter((f) => f.endsWith(".ts")),
    );
    const program2 = buildFixtureProgram(
      FIXTURE_FILES.filter((f) => f.endsWith(".ts")),
    );
    const r1 = await runComplianceAgainst(FIXTURE_FILES, program1, MOCK_VEP, CTX);
    const r2 = await runComplianceAgainst(FIXTURE_FILES, program2, MOCK_VEP, CTX);

    expect(stableStringify(r1.artifact)).toBe(stableStringify(r2.artifact));
    expect(stableStringify(r1.findings)).toBe(stableStringify(r2.findings));
  });

  it("every row has exactly six principle cells populated", async () => {
    const program = buildFixtureProgram(
      FIXTURE_FILES.filter((f) => f.endsWith(".ts")),
    );
    const result = await runComplianceAgainst(FIXTURE_FILES, program, MOCK_VEP, CTX);

    for (const row of result.artifact.rows) {
      expect(Object.keys(row.cells).sort()).toEqual(["I", "II", "III", "IV", "V", "VI"]);
      for (const v of Object.values(row.cells)) {
        expect(["yes", "partial", "no", "n/a"]).toContain(v);
      }
    }
  });
});
